server {
	listen 127.0.0.1:8080;
	server_name localhost;

	client_max_body_size 1M;

	root ./www;
	index index.html;

	location / 
	{
		limit_except GET 
		{
			deny all;
		}
	}

	location /upload 
	{
		limit_except GET POST {
			deny all;
		}
		upload_dir ./www/uploads/;
	}

	location /cgi-bin/ 
	{
		limit_except GET POST {
			deny all;
		}
		cgi_path /usr/bin/python3;
		cgi_extension .py;
	}

	location /redirect/ 
	{
		limit_except GET {
			deny all;
		}
		return 302 https://google.com;
	}
}
