server {
	listen 127.0.0.1:8080;
	server_name localhost;
	client_max_body_size 1M;
	root ./www;
	index index.html;
	location / {
		limit_except GET {
			deny all;
		}
	}
}

server {
	listen 127.0.0.1:8080;
	server_name example.com;
	client_max_body_size 1M;
	root ./www2;
	index index.html;
	location / {
		limit_except GET {
			deny all;
		}
	}
}
